### ISSUE TITLE
Use of Automapper for DTO -> Entity

### ISSUE THREAD

**Issue by tafs7** [jbogard/ContosoUniversity#11]
I was under the impression that you (@jbogard) was rather against the notion of using Automapper to map from DTOs back into an Entity/Domain object.

However, this sample is filled with that usage, where you take in a Command object (a DTO) and map it to the EF entity.

Why did you use this approach? Just for the sake of "learning".  Would you actually do it this way in "real life"?

**Comment by jbogard** [comment]
I generally don't but for very simple cases. Which in the real world, isn't usually the case.
