### ISSUE TITLE
Autofac?

### ISSUE THREAD

**Issue by TDK1964** [jbogard/ContosoUniversity#19]
for example what would this look like in AF?

```
private static IElementGenerator<T> GetGenerator<T>(T model) where T : class
{
      var library = StructuremapMvc.ParentScope.CurrentNestedContainer.GetInstance<HtmlConventionLibrary>();
      return ElementGenerator<T>.For(library, t => StructuremapMvc.ParentScope.CurrentNestedContainer.GetInstance(t), model);
}
```

**Comment by jbogard** [comment]
I dunno, I've never used Autofac. I wouldn't know where to begin.

**Comment by TDK1964** [comment]
@jbogard That's a shame. 
Would you consider your Contoso implementation suitable to use as a template going forward?

**Comment by jbogard** [comment]
Suitable template for...? It's our internal template for new projects if
that's what you mean.

**Comment by TDK1964** [comment]
Yes, that's what I meant. I was thinking of adapting it for Autofac and using it as my project template. Got everything working except that darn GetGenerator method.
