### ISSUE TITLE
Why is MvcTransactionFilter related to SchoolContext ?

### ISSUE THREAD

**Issue by akarzazi** [jbogard/ContosoUniversity#31]
MvcTransactionFilter works only for SchoolContext.

```
 public class MvcTransactionFilter : ActionFilterAttribute
    {
        public override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            // Logger.Instance.Verbose("MvcTransactionFilter::OnActionExecuting");
            var context = StructuremapMvc.ParentScope.CurrentNestedContainer.GetInstance<SchoolContext>();
            context.BeginTransaction();
        }

    ...
}
```

Is there a way to make MvcTransactionFilter work for multiple datacontexts ?
By the way the multiple contexts may want to share the same transaction scope.

**Comment by jbogard** [comment]
Do you have a better option? I don't really have your situation.

**Comment by akarzazi** [comment]
The name "MvcTransactionFilter" is misleading ( and somewhat a lie :) ) 
The real name is "MvcSchoolContextTransactionFilter".

Actually, I came here looking for the "supposed" better approach ^^.

Did you use this approach in real apps ? Therefore those apps do have a single context ?

**Comment by jbogard** [comment]
Ok......in general I don't try to implement a single approach that works for every situation. I rely on my teams to understand their specific situation and adapt an approach as needed. 

And yes, my apps have a single DbContext. Single DB, single context. If my apps are talking to multiple DBs, I have a different problem.

If you need an ambient transaction, you can also do a System.Transactions transaction. But not all my apps need it. So I'm not interested in creating the One Transaction Filter To Rule Them All. I have an approach, a filter that manages transactions, and then adapt as necessary.

**Comment by akarzazi** [comment]
Indeed, the preferred solution would be a business ambient transaction that is assigned automatically to injected Dbcontexts and that could be injected as a dependency for a use in something else than EF.

If the positioning of a beginTransaction is quite simple, the commitTransaction timing is more complicated.
As some actions like "email notification" would need to ensure that the transaction has successfully completed before firing.

**Comment by jbogard** [comment]
OK, lemme know what you come up with!

**Comment by JohnMarsing** [comment]
This won’t add a new department.  

I get an error “The highlighted fields are required to submit this form” which is found in the javascript function  **showSummary** of \js\site.js (line 42).

I don’t know enough of JavaScript to figure out how to debug it, nor do I know enough of your approach to building ASP.Net MVC web apps (but am definitely trying to learn as it looks very cool)

Thanks,
John Marsing

![department create error administrator required by it really is](https://cloud.githubusercontent.com/assets/1078267/20204909/2bad6c9e-a791-11e6-9eef-4bfb1d6bbcaa.png)
