### ISSUE TITLE
Question: indexer on foreach

### ISSUE THREAD

**Issue by DominiqueFonteyn** [jbogard/ContosoUniversity#36]
Hi, 

I have question about the syntax you used in some of the Index pages. For instance, [Course - Index](https://github.com/jbogard/ContosoUniversity/blob/master/src/ContosoUniversity/Features/Course/Index.cshtml)

There is a `foreach `loop that creates a table row for each Course, but instead of using the `item `variable you use an indexer to access the properties of that Course.

` @Html.Display(modelItem => modelItem.Courses[i].CourseID)`

What is the reason for doing it like this? 

Thanks for helping me out.

**Comment by jbogard** [comment]
It’s part of a demo around putting unique IDs for table rows for view
screens.
