### ISSUE TITLE
FxCop CA1034

### ISSUE THREAD

**Issue by collinbarrett** [jbogard/ContosoUniversity#37]
Hey Jimmy,

I've been using MediatR on a couple projects for the last 6 months and love it.

I've seen in many of your examples that [you use nested types](https://github.com/jbogard/ContosoUniversity/blob/a8d396f3df0f2db85ad8fc92125a1334cee015aa/src/ContosoUniversity/Features/Course/Create.cs#L11) often for encapsulating your commands/queries. FxCop flags the [CA1034 warning](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1034-nested-types-should-not-be-visible) when using this pattern. Is that CA1034 rule anything we should be concerned about when using MediatR?

Thanks!

**Comment by jbogard** [comment]
No that’s just a style preference.
